FROM nfnty/arch-mini:latest AS base

RUN mkdir -p /code/node_modules/bcoin /data
WORKDIR /code/node_modules/bcoin
ENTRYPOINT ["node"]
CMD ["/code/scripts/docker-bcoin-init.js"]

RUN pacman -Sy --noconfirm archlinux-keyring && \
    pacman -Syu --noconfirm nodejs npm && \
    rm /var/cache/pacman/pkg/*

FROM base AS build
# Install build dependencies
RUN pacman -Syu --noconfirm base-devel unrar git python2

ARG repo=https://github.com/bcoin-org/bcoin.git
ARG branch=master

# Install bcoin
RUN git clone --branch $branch $repo /code/node_modules/bcoin
RUN npm install --production

FROM base
COPY --from=build /code/node_modules/bcoin /code/node_modules/bcoin
COPY ./scripts/ /code/scripts
