FROM nfnty/arch-mini:latest AS base

RUN mkdir -p /code/node_modules/bcoin /data
WORKDIR /code/node_modules/bcoin

RUN pacman -Sy --noconfirm archlinux-keyring && \
    pacman -Syu --noconfirm nodejs npm && \
    rm /var/cache/pacman/pkg/*

FROM base AS build

# Install build dependencies
# Note: node-gyp needs python
RUN pacman -Syu --noconfirm base-devel unrar git python2 \
    && ln -s /usr/bin/python2 /usr/bin/python

ARG branch=master

# use this to bust the build cache
ARG rebuild=0

# Install bcoin
RUN git clone --branch $branch \
    https://github.com/bcoin-org/bcoin.git /code/node_modules/bcoin \
    && pushd /code/node_modules/bcoin \
    && npm install --production \
    && popd

# Install bmultisig
RUN git clone --branch $branch \
    https://github.com/bcoin-org/bmultisig.git /code/node_modules/bmultisig \
    && pushd /code/node_modules/bmultisig \
    && npm install --production \
    && popd

# Install blgr
RUN git clone --branch $branch \
    https://github.com/bcoin-org/blgr /code/node_modules/blgr \
    && pushd /code/node_modules/blgr \
    && npm install --production \
    && popd

# Install bclient
RUN git clone --branch $branch \
    https://github.com/bcoin-org/bclient.git /code/node_modules/bclient \
    && pushd /code/node_modules/bclient \
    && npm install --production \
    && popd

# TODO: Inherit from official image
FROM base

COPY --from=build /code/node_modules/bcoin /code/node_modules/bcoin
COPY --from=build /code/node_modules/bmultisig /code/node_modules/bmultisig
COPY --from=build /code/node_modules/blgr /code/node_modules/blgr
COPY --from=build /code/node_modules/bclient /code/node_modules/bclient
COPY ./scripts/ /code/scripts

CMD ["/code/scripts/entrypoint.sh"]
