export const ADD_RECENT_BLOCK = 'ADD_RECENT_BLOCK';
export const BLOCK_CONNECT = 'BLOCK_CONNECT';
export const EMIT_SOCKET = 'EMIT_SOCKET';
export const SET_CHAIN_TIP = 'SET_CHAIN_TIP';
export const SET_RECENT_BLOCKS = 'SET_RECENT_BLOCKS';
