export const ADD_NEW_BLOCK = 'ADD_NEW_BLOCK';
export const ADD_RECENT_BLOCK = 'ADD_RECENT_BLOCK';
export const SET_RECENT_BLOCKS = 'SET_RECENT_BLOCKS';
export const SOCKET_CONNECTED = 'SOCKET_CONNECTED';
