export const EMIT_SOCKET = 'EMIT_SOCKET';
export const SOCKET_CONNECTED = 'SOCKET_CONNECTED';
export const ON_WALLET_TX = 'ON_WALLET_TX';
export const ADD_WALLET = 'ADD_WALLET';
export const UPDATE_WALLET = 'UPDATE_WALLET';
export const REMOVE_WALLET = 'REMOVE_WALLET';
